/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/setup-profile`; params?: Router.UnknownInputParams; } | { pathname: `/auth/verify-otp`; params?: Router.UnknownInputParams; } | { pathname: `/client`; params?: Router.UnknownInputParams; } | { pathname: `/client/profile`; params?: Router.UnknownInputParams; } | { pathname: `/client/rides`; params?: Router.UnknownInputParams; } | { pathname: `/client/wallet`; params?: Router.UnknownInputParams; } | { pathname: `/dev/theme-lab`; params?: Router.UnknownInputParams; } | { pathname: `/driver`; params?: Router.UnknownInputParams; } | { pathname: `/driver/rides`; params?: Router.UnknownInputParams; } | { pathname: `/driver/wallet`; params?: Router.UnknownInputParams; } | { pathname: `/driver/profile`; params?: Router.UnknownInputParams; } | { pathname: `/oauth/callback`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/setup-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/verify-otp`; params?: Router.UnknownOutputParams; } | { pathname: `/client`; params?: Router.UnknownOutputParams; } | { pathname: `/client/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/client/rides`; params?: Router.UnknownOutputParams; } | { pathname: `/client/wallet`; params?: Router.UnknownOutputParams; } | { pathname: `/dev/theme-lab`; params?: Router.UnknownOutputParams; } | { pathname: `/driver`; params?: Router.UnknownOutputParams; } | { pathname: `/driver/rides`; params?: Router.UnknownOutputParams; } | { pathname: `/driver/wallet`; params?: Router.UnknownOutputParams; } | { pathname: `/driver/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/oauth/callback`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/setup-profile${`?${string}` | `#${string}` | ''}` | `/auth/verify-otp${`?${string}` | `#${string}` | ''}` | `/client${`?${string}` | `#${string}` | ''}` | `/client/profile${`?${string}` | `#${string}` | ''}` | `/client/rides${`?${string}` | `#${string}` | ''}` | `/client/wallet${`?${string}` | `#${string}` | ''}` | `/dev/theme-lab${`?${string}` | `#${string}` | ''}` | `/driver${`?${string}` | `#${string}` | ''}` | `/driver/rides${`?${string}` | `#${string}` | ''}` | `/driver/wallet${`?${string}` | `#${string}` | ''}` | `/driver/profile${`?${string}` | `#${string}` | ''}` | `/oauth/callback${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/setup-profile`; params?: Router.UnknownInputParams; } | { pathname: `/auth/verify-otp`; params?: Router.UnknownInputParams; } | { pathname: `/client`; params?: Router.UnknownInputParams; } | { pathname: `/client/profile`; params?: Router.UnknownInputParams; } | { pathname: `/client/rides`; params?: Router.UnknownInputParams; } | { pathname: `/client/wallet`; params?: Router.UnknownInputParams; } | { pathname: `/dev/theme-lab`; params?: Router.UnknownInputParams; } | { pathname: `/driver`; params?: Router.UnknownInputParams; } | { pathname: `/driver/rides`; params?: Router.UnknownInputParams; } | { pathname: `/driver/wallet`; params?: Router.UnknownInputParams; } | { pathname: `/driver/profile`; params?: Router.UnknownInputParams; } | { pathname: `/oauth/callback`; params?: Router.UnknownInputParams; };
    }
  }
}
